#!/bin/bash

# minutes
CRITICAL=5
WARNING=15

# this works in combination with
# https://github.com/janhieber/batmon

export LC_ALL=en_US.UTF8
INFO=$(upower -i '/org/freedesktop/UPower/devices/DisplayDevice')
STATE=$(echo ${INFO} | awk '{for(i=1;i<=NF;i++) {if($i~"state:") {print $(i+1)}}}')
LEVEL=$(echo ${INFO} | awk '{for(i=1;i<=NF;i++) {if($i~"percentage:") {print $(i+1)}}}')
LEVEL=${LEVEL%.*}

case ${STATE} in
    discharging)
        LIFE=$(echo ${INFO} | awk '{for(i=1;i<=NF;i++) {if($i~"empty:") {print $(i+1)}}}')
        LIFEUNIT=$(echo ${INFO} | awk '{for(i=1;i<=NF;i++) {if($i~"empty:") {print $(i+2)}}}')
        case ${LIFEUNIT} in
            hours)
                HOURS=${LIFE%.*}
                MINUTES=$(echo "(60*(${LIFE}-${HOURS}))/1" | bc)
                ;;
            minutes)
                HOURS=0
                MINUTES=${LIFE%.*}
                ;;
            *)
                echo "ERR"
                ;;
        esac
        INFO=$(printf '%i:%02i' ${HOURS} ${MINUTES})
        # warning color
        if [[ ${HOURS} -eq 0 ]]
        then
            if [[ ${MINUTES} -lt ${CRITICAL} ]]
            then
                EXTRA="#FF2C28"
            elif [[ ${MINUTES} -lt ${WARNING} ]]
            then
                EXTRA="#FFAD2D"
            fi
        fi
        TEXT="${LEVEL} % (${INFO})"
        ;;

    charging)
        TEXT="${LEVEL} % (chr)"
        ;;

    fully-charged)
        TEXT="full"
        ;;

    *)
        TEXT='ERR'
        ;;
esac

echo $TEXT
echo $TEXT
[[ -n ${EXTRA} ]] && echo ${EXTRA}

exit 0

