#!/bin/sh

INTERVAL=2
CRITICAL=95
WARNING=80

# calc usage
export LC_ALL=en_US.UTF8
IDLE=$(mpstat ${INTERVAL} 1 | tail -n 1 | awk '{print $12}')
CPU=$(echo "(100-${IDLE})/1" | bc)

# output text
echo "${CPU}%"
echo "${CPU}%"

# print color, if needed
[[ ${CPU} -gt ${CRITICAL} ]] && echo "#FF2C28" && exit 0
[[ ${CPU} -gt ${WARNING} ]] && echo "#FFAD2D" && exit 0

exit 0

